version: '3.9'

services:

  api:
    build: ../apps/api
    ports:
      - "8000:8000"
    volumes:
      - ../apps/api:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build: ../apps/web
    ports:
      - "3000:3000"
    volumes:
      - ../apps/web:/app
    command: npm run dev
